//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmYeniHesapwEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sales
    {
        public int ID { get; set; }
        public Nullable<int> BILL_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> TABLE_ID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
    
        public virtual tbl_bill tbl_bill { get; set; }
        public virtual tbl_products tbl_products { get; set; }
    }
}
