//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmYeniHesapwEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_actions
    {
        public int ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string PROCESS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual tbl_employees tbl_employees { get; set; }
    }
}
