//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmYeniHesapwEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bill_payment
    {
        public int ID { get; set; }
        public Nullable<int> BILL_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> KDV_AMOUNT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual tbl_bill tbl_bill { get; set; }
        public virtual tbl_customers tbl_customers { get; set; }
        public virtual tbl_payment_type tbl_payment_type { get; set; }
    }
}
