//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmYeniHesapwEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_sales = new HashSet<tbl_sales>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual tbl_categories tbl_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sales> tbl_sales { get; set; }
    }
}
