//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmYeniHesapwEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reservations
    {
        public int ID { get; set; }
        public Nullable<int> CUSTOMERS_ID { get; set; }
        public Nullable<int> TABLE_ID { get; set; }
        public Nullable<int> BILL_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> CUSTOMER_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        public virtual tbl_tables tbl_tables { get; set; }
    }
}
